version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: profitprint-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db

  profitprint-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profitprint-app
    restart: unless-stopped
    ports:
      - "8090:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/profitprint
    volumes:
      # Техкарты и PDF заказов сохраняются в ОДНУ общую папку на диске D:
      - "D:/rabota/printmax_storage/Техкарты_и_Заказы_PDF:/app/server/uploads/pdf"
      - "D:/rabota/printmax_storage/Техкарты_и_Заказы_PDF:/app/server/uploads/tech_cards"
      
      # Складские документы сохраняются в другую отдельную папку
      - "D:/rabota/printmax_storage/Документы_Склада:/app/server/uploads/sklad"
    depends_on:
      - mongodb